// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PaymentsColumns holds the columns for the "payments" table.
	PaymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "details", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_payments", Type: field.TypeUUID},
	}
	// PaymentsTable holds the schema information for the "payments" table.
	PaymentsTable = &schema.Table{
		Name:       "payments",
		Columns:    PaymentsColumns,
		PrimaryKey: []*schema.Column{PaymentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "payments_users_payments",
				Columns:    []*schema.Column{PaymentsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PlansColumns holds the columns for the "plans" table.
	PlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 1000},
		{Name: "price", Type: field.TypeFloat32, SchemaType: map[string]string{"mysql": "decimal(9,2)", "postgres": "numeric(11,2)"}},
		{Name: "currency", Type: field.TypeString},
		{Name: "exchangeable", Type: field.TypeBool, Default: false},
		{Name: "start_from", Type: field.TypeTime},
		{Name: "duration_type", Type: field.TypeEnum, Enums: []string{"days", "months", "years"}},
		{Name: "duration", Type: field.TypeInt16},
		{Name: "auto_notify", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_plans", Type: field.TypeUUID},
	}
	// PlansTable holds the schema information for the "plans" table.
	PlansTable = &schema.Table{
		Name:       "plans",
		Columns:    PlansColumns,
		PrimaryKey: []*schema.Column{PlansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "plans_users_plans",
				Columns:    []*schema.Column{PlansColumns[13]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RecordsColumns holds the columns for the "records" table.
	RecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "declare_for", Type: field.TypeTime},
		{Name: "confirmed_at", Type: field.TypeTime, Nullable: true},
		{Name: "remark", Type: field.TypeString, Nullable: true},
		{Name: "tracking_code", Type: field.TypeString},
		{Name: "payment_records", Type: field.TypeUUID, Unique: true},
		{Name: "subscription_records", Type: field.TypeUUID, Nullable: true},
	}
	// RecordsTable holds the schema information for the "records" table.
	RecordsTable = &schema.Table{
		Name:       "records",
		Columns:    RecordsColumns,
		PrimaryKey: []*schema.Column{RecordsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "records_payments_records",
				Columns:    []*schema.Column{RecordsColumns[5]},
				RefColumns: []*schema.Column{PaymentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "records_subscriptions_records",
				Columns:    []*schema.Column{RecordsColumns[6]},
				RefColumns: []*schema.Column{SubscriptionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "start_from", Type: field.TypeTime},
		{Name: "subscribed_at", Type: field.TypeTime, Nullable: true},
		{Name: "left_at", Type: field.TypeTime, Nullable: true},
		{Name: "plan_subscriptions", Type: field.TypeUUID},
		{Name: "user_subscriptions", Type: field.TypeUUID},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "subscriptions_plans_subscriptions",
				Columns:    []*schema.Column{SubscriptionsColumns[5]},
				RefColumns: []*schema.Column{PlansColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "subscriptions_users_subscriptions",
				Columns:    []*schema.Column{SubscriptionsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "subscription_user_subscriptions_plan_subscriptions",
				Unique:  true,
				Columns: []*schema.Column{SubscriptionsColumns[6], SubscriptionsColumns[5]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "username", Type: field.TypeString, Unique: true, Nullable: true, Size: 15},
		{Name: "password", Type: field.TypeBytes, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
		{Name: "role", Type: field.TypeString, Default: "user"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "active", Type: field.TypeBool, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PaymentsTable,
		PlansTable,
		RecordsTable,
		SubscriptionsTable,
		UsersTable,
	}
)

func init() {
	PaymentsTable.ForeignKeys[0].RefTable = UsersTable
	PlansTable.ForeignKeys[0].RefTable = UsersTable
	RecordsTable.ForeignKeys[0].RefTable = PaymentsTable
	RecordsTable.ForeignKeys[1].RefTable = SubscriptionsTable
	SubscriptionsTable.ForeignKeys[0].RefTable = PlansTable
	SubscriptionsTable.ForeignKeys[1].RefTable = UsersTable
}
