// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PlansColumns holds the columns for the "plans" table.
	PlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 1000},
		{Name: "price", Type: field.TypeFloat32, SchemaType: map[string]string{"mysql": "decimal(9,2)", "postgres": "numeric(11,2)"}},
		{Name: "currency", Type: field.TypeString},
		{Name: "exchangeable", Type: field.TypeBool, Default: false},
		{Name: "start_from", Type: field.TypeTime},
		{Name: "duration_type", Type: field.TypeEnum, Enums: []string{"days", "months", "years"}},
		{Name: "duration", Type: field.TypeInt16},
		{Name: "auto_notify", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_plans", Type: field.TypeUUID},
	}
	// PlansTable holds the schema information for the "plans" table.
	PlansTable = &schema.Table{
		Name:       "plans",
		Columns:    PlansColumns,
		PrimaryKey: []*schema.Column{PlansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "plans_users_plans",
				Columns:    []*schema.Column{PlansColumns[13]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SubscribesColumns holds the columns for the "subscribes" table.
	SubscribesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "subscribed_at", Type: field.TypeTime, Nullable: true},
		{Name: "left_at", Type: field.TypeTime, Nullable: true},
		{Name: "plan_subscriptions", Type: field.TypeUUID},
		{Name: "user_subscriptions", Type: field.TypeUUID},
	}
	// SubscribesTable holds the schema information for the "subscribes" table.
	SubscribesTable = &schema.Table{
		Name:       "subscribes",
		Columns:    SubscribesColumns,
		PrimaryKey: []*schema.Column{SubscribesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "subscribes_plans_subscriptions",
				Columns:    []*schema.Column{SubscribesColumns[4]},
				RefColumns: []*schema.Column{PlansColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "subscribes_users_subscriptions",
				Columns:    []*schema.Column{SubscribesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "subscribe_user_subscriptions_plan_subscriptions",
				Unique:  true,
				Columns: []*schema.Column{SubscribesColumns[5], SubscribesColumns[4]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "username", Type: field.TypeString, Unique: true, Nullable: true, Size: 15},
		{Name: "password", Type: field.TypeBytes, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
		{Name: "role", Type: field.TypeString, Default: "user"},
		{Name: "active", Type: field.TypeBool, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PlansTable,
		SubscribesTable,
		UsersTable,
	}
)

func init() {
	PlansTable.ForeignKeys[0].RefTable = UsersTable
	SubscribesTable.ForeignKeys[0].RefTable = PlansTable
	SubscribesTable.ForeignKeys[1].RefTable = UsersTable
}
