// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cyclic/ent/payment"
	"cyclic/ent/record"
	"cyclic/ent/subscription"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Record is the model entity for the Record schema.
type Record struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DeclareFor holds the value of the "declare_for" field.
	DeclareFor time.Time `json:"declare_for,omitempty"`
	// ConfirmedAt holds the value of the "confirmed_at" field.
	ConfirmedAt time.Time `json:"confirmed_at,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark string `json:"remark,omitempty"`
	// TrackingCode holds the value of the "tracking_code" field.
	TrackingCode string `json:"tracking_code,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RecordQuery when eager-loading is set.
	Edges                RecordEdges `json:"edges"`
	payment_records      *uuid.UUID
	subscription_records *uuid.UUID
	selectValues         sql.SelectValues
}

// RecordEdges holds the relations/edges for other nodes in the graph.
type RecordEdges struct {
	// Subscription holds the value of the subscription edge.
	Subscription *Subscription `json:"subscription,omitempty"`
	// Payment holds the value of the payment edge.
	Payment *Payment `json:"payment,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecordEdges) SubscriptionOrErr() (*Subscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: subscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// PaymentOrErr returns the Payment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecordEdges) PaymentOrErr() (*Payment, error) {
	if e.Payment != nil {
		return e.Payment, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: payment.Label}
	}
	return nil, &NotLoadedError{edge: "payment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Record) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case record.FieldRemark, record.FieldTrackingCode:
			values[i] = new(sql.NullString)
		case record.FieldDeclareFor, record.FieldConfirmedAt:
			values[i] = new(sql.NullTime)
		case record.FieldID:
			values[i] = new(uuid.UUID)
		case record.ForeignKeys[0]: // payment_records
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case record.ForeignKeys[1]: // subscription_records
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Record fields.
func (r *Record) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case record.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				r.ID = *value
			}
		case record.FieldDeclareFor:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field declare_for", values[i])
			} else if value.Valid {
				r.DeclareFor = value.Time
			}
		case record.FieldConfirmedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_at", values[i])
			} else if value.Valid {
				r.ConfirmedAt = value.Time
			}
		case record.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				r.Remark = value.String
			}
		case record.FieldTrackingCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tracking_code", values[i])
			} else if value.Valid {
				r.TrackingCode = value.String
			}
		case record.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field payment_records", values[i])
			} else if value.Valid {
				r.payment_records = new(uuid.UUID)
				*r.payment_records = *value.S.(*uuid.UUID)
			}
		case record.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_records", values[i])
			} else if value.Valid {
				r.subscription_records = new(uuid.UUID)
				*r.subscription_records = *value.S.(*uuid.UUID)
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Record.
// This includes values selected through modifiers, order, etc.
func (r *Record) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// QuerySubscription queries the "subscription" edge of the Record entity.
func (r *Record) QuerySubscription() *SubscriptionQuery {
	return NewRecordClient(r.config).QuerySubscription(r)
}

// QueryPayment queries the "payment" edge of the Record entity.
func (r *Record) QueryPayment() *PaymentQuery {
	return NewRecordClient(r.config).QueryPayment(r)
}

// Update returns a builder for updating this Record.
// Note that you need to call Record.Unwrap() before calling this method if this Record
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Record) Update() *RecordUpdateOne {
	return NewRecordClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Record entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Record) Unwrap() *Record {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Record is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Record) String() string {
	var builder strings.Builder
	builder.WriteString("Record(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("declare_for=")
	builder.WriteString(r.DeclareFor.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("confirmed_at=")
	builder.WriteString(r.ConfirmedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(r.Remark)
	builder.WriteString(", ")
	builder.WriteString("tracking_code=")
	builder.WriteString(r.TrackingCode)
	builder.WriteByte(')')
	return builder.String()
}

// Records is a parsable slice of Record.
type Records []*Record
