// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cyclic/ent/payment"
	"cyclic/ent/record"
	"cyclic/ent/subscription"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RecordCreate is the builder for creating a Record entity.
type RecordCreate struct {
	config
	mutation *RecordMutation
	hooks    []Hook
}

// SetDeclareFor sets the "declare_for" field.
func (rc *RecordCreate) SetDeclareFor(t time.Time) *RecordCreate {
	rc.mutation.SetDeclareFor(t)
	return rc
}

// SetConfirmedAt sets the "confirmed_at" field.
func (rc *RecordCreate) SetConfirmedAt(t time.Time) *RecordCreate {
	rc.mutation.SetConfirmedAt(t)
	return rc
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (rc *RecordCreate) SetNillableConfirmedAt(t *time.Time) *RecordCreate {
	if t != nil {
		rc.SetConfirmedAt(*t)
	}
	return rc
}

// SetRemark sets the "remark" field.
func (rc *RecordCreate) SetRemark(s string) *RecordCreate {
	rc.mutation.SetRemark(s)
	return rc
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (rc *RecordCreate) SetNillableRemark(s *string) *RecordCreate {
	if s != nil {
		rc.SetRemark(*s)
	}
	return rc
}

// SetTrackingCode sets the "tracking_code" field.
func (rc *RecordCreate) SetTrackingCode(s string) *RecordCreate {
	rc.mutation.SetTrackingCode(s)
	return rc
}

// SetID sets the "id" field.
func (rc *RecordCreate) SetID(u uuid.UUID) *RecordCreate {
	rc.mutation.SetID(u)
	return rc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (rc *RecordCreate) SetNillableID(u *uuid.UUID) *RecordCreate {
	if u != nil {
		rc.SetID(*u)
	}
	return rc
}

// SetSubscriptionID sets the "subscription" edge to the Subscription entity by ID.
func (rc *RecordCreate) SetSubscriptionID(id uuid.UUID) *RecordCreate {
	rc.mutation.SetSubscriptionID(id)
	return rc
}

// SetNillableSubscriptionID sets the "subscription" edge to the Subscription entity by ID if the given value is not nil.
func (rc *RecordCreate) SetNillableSubscriptionID(id *uuid.UUID) *RecordCreate {
	if id != nil {
		rc = rc.SetSubscriptionID(*id)
	}
	return rc
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (rc *RecordCreate) SetSubscription(s *Subscription) *RecordCreate {
	return rc.SetSubscriptionID(s.ID)
}

// SetPaymentID sets the "payment" edge to the Payment entity by ID.
func (rc *RecordCreate) SetPaymentID(id uuid.UUID) *RecordCreate {
	rc.mutation.SetPaymentID(id)
	return rc
}

// SetPayment sets the "payment" edge to the Payment entity.
func (rc *RecordCreate) SetPayment(p *Payment) *RecordCreate {
	return rc.SetPaymentID(p.ID)
}

// Mutation returns the RecordMutation object of the builder.
func (rc *RecordCreate) Mutation() *RecordMutation {
	return rc.mutation
}

// Save creates the Record in the database.
func (rc *RecordCreate) Save(ctx context.Context) (*Record, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RecordCreate) SaveX(ctx context.Context) *Record {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RecordCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RecordCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RecordCreate) defaults() {
	if _, ok := rc.mutation.ID(); !ok {
		v := record.DefaultID()
		rc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RecordCreate) check() error {
	if _, ok := rc.mutation.DeclareFor(); !ok {
		return &ValidationError{Name: "declare_for", err: errors.New(`ent: missing required field "Record.declare_for"`)}
	}
	if _, ok := rc.mutation.TrackingCode(); !ok {
		return &ValidationError{Name: "tracking_code", err: errors.New(`ent: missing required field "Record.tracking_code"`)}
	}
	if _, ok := rc.mutation.PaymentID(); !ok {
		return &ValidationError{Name: "payment", err: errors.New(`ent: missing required edge "Record.payment"`)}
	}
	return nil
}

func (rc *RecordCreate) sqlSave(ctx context.Context) (*Record, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RecordCreate) createSpec() (*Record, *sqlgraph.CreateSpec) {
	var (
		_node = &Record{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(record.Table, sqlgraph.NewFieldSpec(record.FieldID, field.TypeUUID))
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := rc.mutation.DeclareFor(); ok {
		_spec.SetField(record.FieldDeclareFor, field.TypeTime, value)
		_node.DeclareFor = value
	}
	if value, ok := rc.mutation.ConfirmedAt(); ok {
		_spec.SetField(record.FieldConfirmedAt, field.TypeTime, value)
		_node.ConfirmedAt = value
	}
	if value, ok := rc.mutation.Remark(); ok {
		_spec.SetField(record.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := rc.mutation.TrackingCode(); ok {
		_spec.SetField(record.FieldTrackingCode, field.TypeString, value)
		_node.TrackingCode = value
	}
	if nodes := rc.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.SubscriptionTable,
			Columns: []string{record.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.subscription_records = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.PaymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   record.PaymentTable,
			Columns: []string{record.PaymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.payment_records = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RecordCreateBulk is the builder for creating many Record entities in bulk.
type RecordCreateBulk struct {
	config
	err      error
	builders []*RecordCreate
}

// Save creates the Record entities in the database.
func (rcb *RecordCreateBulk) Save(ctx context.Context) ([]*Record, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Record, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RecordCreateBulk) SaveX(ctx context.Context) []*Record {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RecordCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RecordCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
