// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cyclic/ent/predicate"
	"cyclic/ent/record"
	"cyclic/ent/subscription"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RecordUpdate is the builder for updating Record entities.
type RecordUpdate struct {
	config
	hooks    []Hook
	mutation *RecordMutation
}

// Where appends a list predicates to the RecordUpdate builder.
func (ru *RecordUpdate) Where(ps ...predicate.Record) *RecordUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetConfirmedAt sets the "confirmed_at" field.
func (ru *RecordUpdate) SetConfirmedAt(t time.Time) *RecordUpdate {
	ru.mutation.SetConfirmedAt(t)
	return ru
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (ru *RecordUpdate) SetNillableConfirmedAt(t *time.Time) *RecordUpdate {
	if t != nil {
		ru.SetConfirmedAt(*t)
	}
	return ru
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (ru *RecordUpdate) ClearConfirmedAt() *RecordUpdate {
	ru.mutation.ClearConfirmedAt()
	return ru
}

// SetRemark sets the "remark" field.
func (ru *RecordUpdate) SetRemark(s string) *RecordUpdate {
	ru.mutation.SetRemark(s)
	return ru
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (ru *RecordUpdate) SetNillableRemark(s *string) *RecordUpdate {
	if s != nil {
		ru.SetRemark(*s)
	}
	return ru
}

// ClearRemark clears the value of the "remark" field.
func (ru *RecordUpdate) ClearRemark() *RecordUpdate {
	ru.mutation.ClearRemark()
	return ru
}

// SetSubscriptionID sets the "subscription" edge to the Subscription entity by ID.
func (ru *RecordUpdate) SetSubscriptionID(id uuid.UUID) *RecordUpdate {
	ru.mutation.SetSubscriptionID(id)
	return ru
}

// SetNillableSubscriptionID sets the "subscription" edge to the Subscription entity by ID if the given value is not nil.
func (ru *RecordUpdate) SetNillableSubscriptionID(id *uuid.UUID) *RecordUpdate {
	if id != nil {
		ru = ru.SetSubscriptionID(*id)
	}
	return ru
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (ru *RecordUpdate) SetSubscription(s *Subscription) *RecordUpdate {
	return ru.SetSubscriptionID(s.ID)
}

// Mutation returns the RecordMutation object of the builder.
func (ru *RecordUpdate) Mutation() *RecordMutation {
	return ru.mutation
}

// ClearSubscription clears the "subscription" edge to the Subscription entity.
func (ru *RecordUpdate) ClearSubscription() *RecordUpdate {
	ru.mutation.ClearSubscription()
	return ru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RecordUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RecordUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RecordUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RecordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(record.Table, record.Columns, sqlgraph.NewFieldSpec(record.FieldID, field.TypeUUID))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.ConfirmedAt(); ok {
		_spec.SetField(record.FieldConfirmedAt, field.TypeTime, value)
	}
	if ru.mutation.ConfirmedAtCleared() {
		_spec.ClearField(record.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := ru.mutation.Remark(); ok {
		_spec.SetField(record.FieldRemark, field.TypeString, value)
	}
	if ru.mutation.RemarkCleared() {
		_spec.ClearField(record.FieldRemark, field.TypeString)
	}
	if ru.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.SubscriptionTable,
			Columns: []string{record.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.SubscriptionTable,
			Columns: []string{record.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{record.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RecordUpdateOne is the builder for updating a single Record entity.
type RecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecordMutation
}

// SetConfirmedAt sets the "confirmed_at" field.
func (ruo *RecordUpdateOne) SetConfirmedAt(t time.Time) *RecordUpdateOne {
	ruo.mutation.SetConfirmedAt(t)
	return ruo
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (ruo *RecordUpdateOne) SetNillableConfirmedAt(t *time.Time) *RecordUpdateOne {
	if t != nil {
		ruo.SetConfirmedAt(*t)
	}
	return ruo
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (ruo *RecordUpdateOne) ClearConfirmedAt() *RecordUpdateOne {
	ruo.mutation.ClearConfirmedAt()
	return ruo
}

// SetRemark sets the "remark" field.
func (ruo *RecordUpdateOne) SetRemark(s string) *RecordUpdateOne {
	ruo.mutation.SetRemark(s)
	return ruo
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (ruo *RecordUpdateOne) SetNillableRemark(s *string) *RecordUpdateOne {
	if s != nil {
		ruo.SetRemark(*s)
	}
	return ruo
}

// ClearRemark clears the value of the "remark" field.
func (ruo *RecordUpdateOne) ClearRemark() *RecordUpdateOne {
	ruo.mutation.ClearRemark()
	return ruo
}

// SetSubscriptionID sets the "subscription" edge to the Subscription entity by ID.
func (ruo *RecordUpdateOne) SetSubscriptionID(id uuid.UUID) *RecordUpdateOne {
	ruo.mutation.SetSubscriptionID(id)
	return ruo
}

// SetNillableSubscriptionID sets the "subscription" edge to the Subscription entity by ID if the given value is not nil.
func (ruo *RecordUpdateOne) SetNillableSubscriptionID(id *uuid.UUID) *RecordUpdateOne {
	if id != nil {
		ruo = ruo.SetSubscriptionID(*id)
	}
	return ruo
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (ruo *RecordUpdateOne) SetSubscription(s *Subscription) *RecordUpdateOne {
	return ruo.SetSubscriptionID(s.ID)
}

// Mutation returns the RecordMutation object of the builder.
func (ruo *RecordUpdateOne) Mutation() *RecordMutation {
	return ruo.mutation
}

// ClearSubscription clears the "subscription" edge to the Subscription entity.
func (ruo *RecordUpdateOne) ClearSubscription() *RecordUpdateOne {
	ruo.mutation.ClearSubscription()
	return ruo
}

// Where appends a list predicates to the RecordUpdate builder.
func (ruo *RecordUpdateOne) Where(ps ...predicate.Record) *RecordUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RecordUpdateOne) Select(field string, fields ...string) *RecordUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Record entity.
func (ruo *RecordUpdateOne) Save(ctx context.Context) (*Record, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RecordUpdateOne) SaveX(ctx context.Context) *Record {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RecordUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RecordUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RecordUpdateOne) sqlSave(ctx context.Context) (_node *Record, err error) {
	_spec := sqlgraph.NewUpdateSpec(record.Table, record.Columns, sqlgraph.NewFieldSpec(record.FieldID, field.TypeUUID))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Record.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, record.FieldID)
		for _, f := range fields {
			if !record.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != record.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.ConfirmedAt(); ok {
		_spec.SetField(record.FieldConfirmedAt, field.TypeTime, value)
	}
	if ruo.mutation.ConfirmedAtCleared() {
		_spec.ClearField(record.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := ruo.mutation.Remark(); ok {
		_spec.SetField(record.FieldRemark, field.TypeString, value)
	}
	if ruo.mutation.RemarkCleared() {
		_spec.ClearField(record.FieldRemark, field.TypeString)
	}
	if ruo.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.SubscriptionTable,
			Columns: []string{record.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   record.SubscriptionTable,
			Columns: []string{record.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Record{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{record.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
