// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cyclic/ent/plan"
	"cyclic/ent/predicate"
	"cyclic/ent/record"
	"cyclic/ent/subscription"
	"cyclic/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SubscriptionUpdate is the builder for updating Subscription entities.
type SubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionMutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (su *SubscriptionUpdate) Where(ps ...predicate.Subscription) *SubscriptionUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetStartFrom sets the "start_from" field.
func (su *SubscriptionUpdate) SetStartFrom(t time.Time) *SubscriptionUpdate {
	su.mutation.SetStartFrom(t)
	return su
}

// SetNillableStartFrom sets the "start_from" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableStartFrom(t *time.Time) *SubscriptionUpdate {
	if t != nil {
		su.SetStartFrom(*t)
	}
	return su
}

// SetSubscribedAt sets the "subscribed_at" field.
func (su *SubscriptionUpdate) SetSubscribedAt(t time.Time) *SubscriptionUpdate {
	su.mutation.SetSubscribedAt(t)
	return su
}

// SetNillableSubscribedAt sets the "subscribed_at" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableSubscribedAt(t *time.Time) *SubscriptionUpdate {
	if t != nil {
		su.SetSubscribedAt(*t)
	}
	return su
}

// ClearSubscribedAt clears the value of the "subscribed_at" field.
func (su *SubscriptionUpdate) ClearSubscribedAt() *SubscriptionUpdate {
	su.mutation.ClearSubscribedAt()
	return su
}

// SetLeftAt sets the "left_at" field.
func (su *SubscriptionUpdate) SetLeftAt(t time.Time) *SubscriptionUpdate {
	su.mutation.SetLeftAt(t)
	return su
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableLeftAt(t *time.Time) *SubscriptionUpdate {
	if t != nil {
		su.SetLeftAt(*t)
	}
	return su
}

// ClearLeftAt clears the value of the "left_at" field.
func (su *SubscriptionUpdate) ClearLeftAt() *SubscriptionUpdate {
	su.mutation.ClearLeftAt()
	return su
}

// SetUserID sets the "user" edge to the User entity by ID.
func (su *SubscriptionUpdate) SetUserID(id uuid.UUID) *SubscriptionUpdate {
	su.mutation.SetUserID(id)
	return su
}

// SetUser sets the "user" edge to the User entity.
func (su *SubscriptionUpdate) SetUser(u *User) *SubscriptionUpdate {
	return su.SetUserID(u.ID)
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (su *SubscriptionUpdate) SetPlanID(id uuid.UUID) *SubscriptionUpdate {
	su.mutation.SetPlanID(id)
	return su
}

// SetPlan sets the "plan" edge to the Plan entity.
func (su *SubscriptionUpdate) SetPlan(p *Plan) *SubscriptionUpdate {
	return su.SetPlanID(p.ID)
}

// AddRecordIDs adds the "records" edge to the Record entity by IDs.
func (su *SubscriptionUpdate) AddRecordIDs(ids ...uuid.UUID) *SubscriptionUpdate {
	su.mutation.AddRecordIDs(ids...)
	return su
}

// AddRecords adds the "records" edges to the Record entity.
func (su *SubscriptionUpdate) AddRecords(r ...*Record) *SubscriptionUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.AddRecordIDs(ids...)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (su *SubscriptionUpdate) Mutation() *SubscriptionMutation {
	return su.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (su *SubscriptionUpdate) ClearUser() *SubscriptionUpdate {
	su.mutation.ClearUser()
	return su
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (su *SubscriptionUpdate) ClearPlan() *SubscriptionUpdate {
	su.mutation.ClearPlan()
	return su
}

// ClearRecords clears all "records" edges to the Record entity.
func (su *SubscriptionUpdate) ClearRecords() *SubscriptionUpdate {
	su.mutation.ClearRecords()
	return su
}

// RemoveRecordIDs removes the "records" edge to Record entities by IDs.
func (su *SubscriptionUpdate) RemoveRecordIDs(ids ...uuid.UUID) *SubscriptionUpdate {
	su.mutation.RemoveRecordIDs(ids...)
	return su
}

// RemoveRecords removes "records" edges to Record entities.
func (su *SubscriptionUpdate) RemoveRecords(r ...*Record) *SubscriptionUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.RemoveRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SubscriptionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SubscriptionUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SubscriptionUpdate) check() error {
	if _, ok := su.mutation.UserID(); su.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Subscription.user"`)
	}
	if _, ok := su.mutation.PlanID(); su.mutation.PlanCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Subscription.plan"`)
	}
	return nil
}

func (su *SubscriptionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.StartFrom(); ok {
		_spec.SetField(subscription.FieldStartFrom, field.TypeTime, value)
	}
	if value, ok := su.mutation.SubscribedAt(); ok {
		_spec.SetField(subscription.FieldSubscribedAt, field.TypeTime, value)
	}
	if su.mutation.SubscribedAtCleared() {
		_spec.ClearField(subscription.FieldSubscribedAt, field.TypeTime)
	}
	if value, ok := su.mutation.LeftAt(); ok {
		_spec.SetField(subscription.FieldLeftAt, field.TypeTime, value)
	}
	if su.mutation.LeftAtCleared() {
		_spec.ClearField(subscription.FieldLeftAt, field.TypeTime)
	}
	if su.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.RecordsTable,
			Columns: []string{subscription.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !su.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.RecordsTable,
			Columns: []string{subscription.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.RecordsTable,
			Columns: []string{subscription.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SubscriptionUpdateOne is the builder for updating a single Subscription entity.
type SubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionMutation
}

// SetStartFrom sets the "start_from" field.
func (suo *SubscriptionUpdateOne) SetStartFrom(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetStartFrom(t)
	return suo
}

// SetNillableStartFrom sets the "start_from" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableStartFrom(t *time.Time) *SubscriptionUpdateOne {
	if t != nil {
		suo.SetStartFrom(*t)
	}
	return suo
}

// SetSubscribedAt sets the "subscribed_at" field.
func (suo *SubscriptionUpdateOne) SetSubscribedAt(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetSubscribedAt(t)
	return suo
}

// SetNillableSubscribedAt sets the "subscribed_at" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableSubscribedAt(t *time.Time) *SubscriptionUpdateOne {
	if t != nil {
		suo.SetSubscribedAt(*t)
	}
	return suo
}

// ClearSubscribedAt clears the value of the "subscribed_at" field.
func (suo *SubscriptionUpdateOne) ClearSubscribedAt() *SubscriptionUpdateOne {
	suo.mutation.ClearSubscribedAt()
	return suo
}

// SetLeftAt sets the "left_at" field.
func (suo *SubscriptionUpdateOne) SetLeftAt(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetLeftAt(t)
	return suo
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableLeftAt(t *time.Time) *SubscriptionUpdateOne {
	if t != nil {
		suo.SetLeftAt(*t)
	}
	return suo
}

// ClearLeftAt clears the value of the "left_at" field.
func (suo *SubscriptionUpdateOne) ClearLeftAt() *SubscriptionUpdateOne {
	suo.mutation.ClearLeftAt()
	return suo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (suo *SubscriptionUpdateOne) SetUserID(id uuid.UUID) *SubscriptionUpdateOne {
	suo.mutation.SetUserID(id)
	return suo
}

// SetUser sets the "user" edge to the User entity.
func (suo *SubscriptionUpdateOne) SetUser(u *User) *SubscriptionUpdateOne {
	return suo.SetUserID(u.ID)
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (suo *SubscriptionUpdateOne) SetPlanID(id uuid.UUID) *SubscriptionUpdateOne {
	suo.mutation.SetPlanID(id)
	return suo
}

// SetPlan sets the "plan" edge to the Plan entity.
func (suo *SubscriptionUpdateOne) SetPlan(p *Plan) *SubscriptionUpdateOne {
	return suo.SetPlanID(p.ID)
}

// AddRecordIDs adds the "records" edge to the Record entity by IDs.
func (suo *SubscriptionUpdateOne) AddRecordIDs(ids ...uuid.UUID) *SubscriptionUpdateOne {
	suo.mutation.AddRecordIDs(ids...)
	return suo
}

// AddRecords adds the "records" edges to the Record entity.
func (suo *SubscriptionUpdateOne) AddRecords(r ...*Record) *SubscriptionUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.AddRecordIDs(ids...)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (suo *SubscriptionUpdateOne) Mutation() *SubscriptionMutation {
	return suo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (suo *SubscriptionUpdateOne) ClearUser() *SubscriptionUpdateOne {
	suo.mutation.ClearUser()
	return suo
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (suo *SubscriptionUpdateOne) ClearPlan() *SubscriptionUpdateOne {
	suo.mutation.ClearPlan()
	return suo
}

// ClearRecords clears all "records" edges to the Record entity.
func (suo *SubscriptionUpdateOne) ClearRecords() *SubscriptionUpdateOne {
	suo.mutation.ClearRecords()
	return suo
}

// RemoveRecordIDs removes the "records" edge to Record entities by IDs.
func (suo *SubscriptionUpdateOne) RemoveRecordIDs(ids ...uuid.UUID) *SubscriptionUpdateOne {
	suo.mutation.RemoveRecordIDs(ids...)
	return suo
}

// RemoveRecords removes "records" edges to Record entities.
func (suo *SubscriptionUpdateOne) RemoveRecords(r ...*Record) *SubscriptionUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.RemoveRecordIDs(ids...)
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (suo *SubscriptionUpdateOne) Where(ps ...predicate.Subscription) *SubscriptionUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SubscriptionUpdateOne) Select(field string, fields ...string) *SubscriptionUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Subscription entity.
func (suo *SubscriptionUpdateOne) Save(ctx context.Context) (*Subscription, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SubscriptionUpdateOne) SaveX(ctx context.Context) *Subscription {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SubscriptionUpdateOne) check() error {
	if _, ok := suo.mutation.UserID(); suo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Subscription.user"`)
	}
	if _, ok := suo.mutation.PlanID(); suo.mutation.PlanCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Subscription.plan"`)
	}
	return nil
}

func (suo *SubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *Subscription, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscription.FieldID)
		for _, f := range fields {
			if !subscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.StartFrom(); ok {
		_spec.SetField(subscription.FieldStartFrom, field.TypeTime, value)
	}
	if value, ok := suo.mutation.SubscribedAt(); ok {
		_spec.SetField(subscription.FieldSubscribedAt, field.TypeTime, value)
	}
	if suo.mutation.SubscribedAtCleared() {
		_spec.ClearField(subscription.FieldSubscribedAt, field.TypeTime)
	}
	if value, ok := suo.mutation.LeftAt(); ok {
		_spec.SetField(subscription.FieldLeftAt, field.TypeTime, value)
	}
	if suo.mutation.LeftAtCleared() {
		_spec.ClearField(subscription.FieldLeftAt, field.TypeTime)
	}
	if suo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.RecordsTable,
			Columns: []string{subscription.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !suo.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.RecordsTable,
			Columns: []string{subscription.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.RecordsTable,
			Columns: []string{subscription.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subscription{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
