// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cyclic/ent/subscribe"
	"cyclic/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SubscribeCreate is the builder for creating a Subscribe entity.
type SubscribeCreate struct {
	config
	mutation *SubscribeMutation
	hooks    []Hook
}

// SetSubscribedAt sets the "subscribed_at" field.
func (sc *SubscribeCreate) SetSubscribedAt(t time.Time) *SubscribeCreate {
	sc.mutation.SetSubscribedAt(t)
	return sc
}

// SetNillableSubscribedAt sets the "subscribed_at" field if the given value is not nil.
func (sc *SubscribeCreate) SetNillableSubscribedAt(t *time.Time) *SubscribeCreate {
	if t != nil {
		sc.SetSubscribedAt(*t)
	}
	return sc
}

// SetLeftAt sets the "left_at" field.
func (sc *SubscribeCreate) SetLeftAt(t time.Time) *SubscribeCreate {
	sc.mutation.SetLeftAt(t)
	return sc
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (sc *SubscribeCreate) SetNillableLeftAt(t *time.Time) *SubscribeCreate {
	if t != nil {
		sc.SetLeftAt(*t)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *SubscribeCreate) SetID(u uuid.UUID) *SubscribeCreate {
	sc.mutation.SetID(u)
	return sc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (sc *SubscribeCreate) SetNillableID(u *uuid.UUID) *SubscribeCreate {
	if u != nil {
		sc.SetID(*u)
	}
	return sc
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (sc *SubscribeCreate) AddUserIDs(ids ...uuid.UUID) *SubscribeCreate {
	sc.mutation.AddUserIDs(ids...)
	return sc
}

// AddUsers adds the "users" edges to the User entity.
func (sc *SubscribeCreate) AddUsers(u ...*User) *SubscribeCreate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return sc.AddUserIDs(ids...)
}

// Mutation returns the SubscribeMutation object of the builder.
func (sc *SubscribeCreate) Mutation() *SubscribeMutation {
	return sc.mutation
}

// Save creates the Subscribe in the database.
func (sc *SubscribeCreate) Save(ctx context.Context) (*Subscribe, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SubscribeCreate) SaveX(ctx context.Context) *Subscribe {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SubscribeCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SubscribeCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SubscribeCreate) defaults() {
	if _, ok := sc.mutation.SubscribedAt(); !ok {
		v := subscribe.DefaultSubscribedAt()
		sc.mutation.SetSubscribedAt(v)
	}
	if _, ok := sc.mutation.ID(); !ok {
		v := subscribe.DefaultID()
		sc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SubscribeCreate) check() error {
	if _, ok := sc.mutation.SubscribedAt(); !ok {
		return &ValidationError{Name: "subscribed_at", err: errors.New(`ent: missing required field "Subscribe.subscribed_at"`)}
	}
	return nil
}

func (sc *SubscribeCreate) sqlSave(ctx context.Context) (*Subscribe, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SubscribeCreate) createSpec() (*Subscribe, *sqlgraph.CreateSpec) {
	var (
		_node = &Subscribe{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(subscribe.Table, sqlgraph.NewFieldSpec(subscribe.FieldID, field.TypeUUID))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := sc.mutation.SubscribedAt(); ok {
		_spec.SetField(subscribe.FieldSubscribedAt, field.TypeTime, value)
		_node.SubscribedAt = value
	}
	if value, ok := sc.mutation.LeftAt(); ok {
		_spec.SetField(subscribe.FieldLeftAt, field.TypeTime, value)
		_node.LeftAt = value
	}
	if nodes := sc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   subscribe.UsersTable,
			Columns: subscribe.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubscribeCreateBulk is the builder for creating many Subscribe entities in bulk.
type SubscribeCreateBulk struct {
	config
	err      error
	builders []*SubscribeCreate
}

// Save creates the Subscribe entities in the database.
func (scb *SubscribeCreateBulk) Save(ctx context.Context) ([]*Subscribe, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Subscribe, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscribeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SubscribeCreateBulk) SaveX(ctx context.Context) []*Subscribe {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SubscribeCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SubscribeCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
