// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Plan is the predicate function for plan builders.
type Plan func(*sql.Selector)

// Subscribe is the predicate function for subscribe builders.
type Subscribe func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
